# Generated by Django 4.0.1 on 2022-01-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_course_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(default='', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='', max_length=36, primary_key=True, serialize=False),
        ),
    ]
